spring:
  datasource:
    url: jdbc:mysql://deeptrain-database.cluster-ckjw6msk2z8l.us-east-1.rds.amazonaws.com:3306/deeptrain?useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    password: XFCampu$123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
